### ISSUE TITLE
Can i bind user ip instead server hostname

### ISSUE THREAD

**Issue by desertknight** [Phalanxia/Maid-IRC#61]
Hi, i just installed Maid-IRC, and look pretty nice, but i have some questions :)
First, can i set (via config, or something), every user to use his ip, instead my server hostname.
Second, will be very useful for me, if i can configure default server configuration, eg i will use only for one network and not necessary user to know which servers use.

Sorry, if questions are already asked, i can't find anything. Any links will be useful.

**Comment by Phalanxia** [comment]
Hi,
Maid-IRC doesn't currently support any form of connecting as a user's IP. The protocol for doing so is called WebIRC. If you wish to provide a patch to Maid-IRC to support this, it should be relatively easy as the IRC library Maid-IRC uses supports it. A starting point would be at https://github.com/Phalanxia/Maid-IRC/blob/master/src/server/modules/maidIrc.js#L38.
Due to external commitments it will be quite a while before I'd be able to implement this, but I'd be happy to answer any questions or review a patch.

Thanks,
Madison

**Comment by desertknight** [comment]
Thanks, @Phalanxia . i will close "issue" for now, thanks again 👍
